import os
import glob
import json
import subprocess
import numpy as np

def find_best_experiment(base_dir="experiments"):
    """Scans all alignment_metrics.txt files to find the config with the highest correlation."""
    best_corr = -1.0
    best_exp_name = None
    best_epoch = None

    # Search for all alignment metrics files generated by validate.py
    search_pattern = os.path.join(base_dir, "*", "monitoring", "ep*", "alignment_metrics.txt")
    metric_files = glob.glob(search_pattern)

    if not metric_files:
        raise FileNotFoundError("No alignment_metrics.txt files found. Have you run validate.py on your experiments yet?")

    for file_path in metric_files:
        with open(file_path, "r") as f:
            lines = f.readlines()
            
        exp_name, epoch, corr = None, None, None
        for line in lines:
            if line.startswith("Experiment:"):
                exp_name = line.split(":", 1)[1].strip()
            elif line.startswith("Epoch:"):
                epoch = int(line.split(":", 1)[1].strip())
            elif line.startswith("Max Pearson Correlation:"):
                corr = float(line.split(":", 1)[1].strip())

        if corr is not None and corr > best_corr:
            best_corr = corr
            best_exp_name = exp_name
            best_epoch = epoch

    print(f"[✔] Best Experiment Found: {best_exp_name}")
    print(f"    Epoch: {best_epoch} | Correlation: {best_corr:.6f}")
    return best_exp_name, best_epoch

def create_seed_configs(best_exp_name, base_dir="experiments", num_seeds=5, output_file="optimal_seeds_config.json"):
    """Reads the specs of the best experiment and duplicates it with different seeds."""
    specs_path = os.path.join(base_dir, best_exp_name, "specs.json")
    
    if not os.path.exists(specs_path):
        raise FileNotFoundError(f"Could not find specs.json for the best experiment at: {specs_path}")

    with open(specs_path, "r") as f:
        base_specs = json.load(f)

    # Remove the commit_hash if it exists so the runner can re-inject the current one
    base_specs.pop("commit_hash", None)

    new_experiments = {}
    seeds = [42, 100, 1337, 2026, 9999] # Hardcoded seeds for reproducibility
    
    print(f"\n[+] Generating {num_seeds} new configurations based on '{best_exp_name}'...")
    for i in range(num_seeds):
        exp_variant_name = f"{best_exp_name}_robustness_seed_{seeds[i]}"
        variant_specs = base_specs.copy()
        variant_specs["seed"] = seeds[i]
        
        new_experiments[exp_variant_name] = variant_specs

    with open(output_file, "w") as f:
        json.dump(new_experiments, f, indent=4)
        
    print(f"[✔] New configuration saved to: {output_file}")
    return output_file, new_experiments.keys()

def run_new_experiments(config_file):
    """Triggers the existing experiment_runner_gpu.py with the new config."""
    print(f"\n[>] Launching experiment_runner_gpu.py with {config_file}...\n")
    # Call your existing multi-processing script
    subprocess.run(["python", "experiment_runner_gpu.py", "--config", config_file], check=True)
    print("\n[✔] All robustness experiments completed.")

def validate_and_aggregate(experiment_names, target_epoch):
    """Runs validate.py on the new experiments and calculates mean/variance."""
    print("\n[>] Running validation on the new seed experiments...")
    correlations = []

    for exp_name in experiment_names:
        print(f"Validating {exp_name} at epoch {target_epoch}...")
        try:
            subprocess.run([
                "python", "validate.py", 
                "--exp_name", exp_name, 
                "--epoch", str(target_epoch)
            ], check=True, stdout=subprocess.DEVNULL) # Suppress output to keep console clean
            
            # Read the newly generated metrics
            metric_file = os.path.join("experiments", exp_name, "monitoring", f"ep{target_epoch}", "alignment_metrics.txt")
            with open(metric_file, "r") as f:
                for line in f.readlines():
                    if line.startswith("Max Pearson Correlation:"):
                        corr = float(line.split(":", 1)[1].strip())
                        correlations.append(corr)
                        print(f"  -> Correlation: {corr:.6f}")
        except Exception as e:
            print(f"  [!] Failed to validate {exp_name}: {e}")

    if correlations:
        mean_corr = np.mean(correlations)
        var_corr = np.var(correlations)
        std_corr = np.std(correlations)
        
        print("\n" + "="*50)
        print("📊 FINAL ROBUSTNESS STATISTICS")
        print("="*50)
        print(f"Number of Runs: {len(correlations)}")
        print(f"Mean Correlation:  {mean_corr:.6f}")
        print(f"Variance:          {var_corr:.6f}")
        print(f"Standard Dev:      {std_corr:.6f}")
        print("="*50)

if __name__ == "__main__":
    # 1. Parse previous results to find the best configuration
    best_exp, best_epoch = find_best_experiment()
    
    # 2. Generate 5 new setups varying only the seed
    config_file, new_exp_names = create_seed_configs(best_exp, num_seeds=5)
    
    # 3. Train the new models using your existing runner
    run_new_experiments(config_file)
    
    # 4. Validate the newly trained models and compute Mean & Variance
    validate_and_aggregate(new_exp_names, best_epoch)